services:
  service-admin-backend:
    build: ./adminService
    container_name: service-admin-backend
    ports:
      - "3001:3000"
    restart: always
    env_file:
      - adminService/.env
    volumes:
      - ./uploads:/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    depends_on:
      admin-db:
        condition: service_healthy
    networks:
      - aldeiaviva_network

  admin-db:
    image: mysql:8.0
    container_name: admin-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: admindb
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - admin_data:/var/lib/mysql
    networks:
      - aldeiaviva_network

  loki:
    image: grafana/loki
    container_name: loki
    restart: always
    user: "0"
    command: ["-config.file=/etc/loki/loki.yml"]
    ports:
      - "3100:3100"
    volumes:
      - ./docker/loki/loki.yml:/etc/loki/loki.yml:ro
      - loki_data:/var/loki
    networks:
      - aldeiaviva_network
  
  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    restart: always

    command:
      - -config.file=/etc/promtail/promtail.yml

    volumes:
      - ./docker/promtail/promtail.yml:/etc/promtail/promtail.yml:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

    depends_on:
      - loki

    networks:
      - aldeiaviva_network

  grafana:
    image: grafana/grafana
    restart: always
    container_name: grafana
    depends_on:
      loki:
        condition: service_started
    ports:
      - 3002:3000
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana:/var/lib/grafana
      - ./docker/grafana/provisioning/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
    networks:
      - aldeiaviva_network
  
  redis-admin:
    image: redis:7
    container_name: redis-admin
    restart: always
    ports:
      - "6379:6379"
    networks:
      - aldeiaviva_network

  nginx-admin:
    image: nginx:alpine
    container_name: nginx-admin
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./uploads:/usr/share/nginx/uploads:ro
    ports:
      - "8080:8080"
    depends_on:
      service-admin-backend:
        condition: service_healthy
    networks:
      - aldeiaviva_network

volumes:
  admin_data:
  loki_data:
  grafana:

networks:
  aldeiaviva_network:
    driver: bridge